package com.lsystem.model;
import com.lsystem.view.NonTerminal;
import java.util.ArrayList;


public class NonTerminalExpander {

    RecursiveLsystem lsystem;
    ArrayList<NonTerminal> nonTerminalsInPoint;
    ArrayList<String> subStrings;
    public NonTerminalExpander(ArrayList<NonTerminal> nonTerminalsInPoint, RecursiveLsystem lsystem) {
        this.nonTerminalsInPoint = nonTerminalsInPoint;
        this.lsystem = lsystem;
        checkArray();
    }

    /**
     * Creates subtrees, which are needed to expand a specific bud in the tree.
     * <p>
     *     This contains a for-loop that runs for every nonTerminal that is pressed.
     *     This is necessary because there could be two or more nonTerminal ('buds') pressed at the same time,
     *     as they are sometimes placed on top of each other.
     *
     *     This method devides the tree String in to parts (subtrees).
     *
     *     The substring could look something like this:
     *     First substring is the part of the string before the nonterminal.
     *     Second substring is the nonterminal that needs to be expanded.
     *     Third substring is the part of the string after the nonTerminal.
     *
     * </p>
     */
    private void checkArray() {
        String currentTreeString = lsystem.getTreeString();
        subStrings = new ArrayList<String>();
        int j = 0;

        for (int i = 0; i < nonTerminalsInPoint.size(); i++) {
            String subString1 = currentTreeString.substring(j, nonTerminalsInPoint.get(i).getI());
            subStrings.add(subString1);

            if (i < nonTerminalsInPoint.size() - 1) {
                String subString2 = "" + nonTerminalsInPoint.get(i).getC();
                String expandedString2 = lsystem.expand(subString2, 1);
                subStrings.add(expandedString2);

                j = nonTerminalsInPoint.get(i).getI() + 1;
            }
            else {
                String subString3 = "" + nonTerminalsInPoint.get(i).getC();
                String expandedString1 = lsystem.expand(subString3, 1);
                subStrings.add(expandedString1);
                String subString4 = currentTreeString.substring(nonTerminalsInPoint.get(i).getI() + 1, currentTreeString.length());
                subStrings.add(subString4);
            }
        }
        combineSubTrees();


    }

    /**
     * Combines the String to one new tree String
     * <p>
     *     This Combines the substrings from the previous method to one string in a foreach loop.
     *     Last the treeString is sat as the new Tree, generated by this method.
     * </p>
     */
    private void combineSubTrees() {
        String newTree = "";
        for (String s : subStrings) {
            newTree += s;
        }
        lsystem.setTreeString(newTree);
    }
}
